

export const HELLO_WORLD = 'HELLO_WORLD';
export const REDUX_RESET_STATE = 'REDUX_RESET_STATE';

export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

// auth constants
export const AUTH_UPDATE_REGISTER_FORM_FIELD = 'AUTH_UPDATE_REGISTER_FORM_FIELD';
export const AUTH_SUBMIT_REGISTER_FORM = 'AUTH_SUBMIT_REGISTER_FORM';
export const AUTH_INVALIDATE_REGISTER_FORM = 'AUTH_INVALIDATE_REGISTER_FORM';
export const AUTH_RESET_REGISTER_FORM_FIELDS = 'AUTH_RESET_REGISTER_FORM_FIELDS';

export const AUTH_UPDATE_USER_DATA = 'AUTH_UPDATE_USER_DATA';
export const AUTH_RESET_USER_DATA = 'AUTH_RESET_USER_DATA';
export const AUTH_UPDATE_USER_FIELD = 'AUTH_UPDATE_USER_FIELD';

export const AUTH_UPDATE_LOGIN_FORM_FIELD = 'AUTH_UPDATE_LOGIN_FORM_FIELD';
export const AUTH_SUBMIT_LOGIN_FORM = 'AUTH_SUBMIT_LOGIN_FORM';
export const AUTH_INVALIDATE_LOGIN_FORM = 'AUTH_INVALIDATE_LOGIN_FORM';
export const AUTH_RESET_LOGIN_FORM_FIELDS = 'AUTH_RESET_LOGIN_FORM_FIELDS';

export const AUTH_SUBMIT_RESET_PASSWORD_FORM = 'AUTH_SUBMIT_RESET_PASSWORD_FORM';
export const AUTH_UPDATE_RESET_PASSWORD_STATUS_FIELD = 'AUTH_UPDATE_RESET_PASSWORD_STATUS_FIELD';
export const AUTH_INVALIDATE_RESET_PASSWORD_FORM = 'AUTH_INVALIDATE_RESET_PASSWORD_FORM';

export const USER_PROFILE_LOADED = 'USER_PROFILE_LOADED';
export const USER_UPDATE_PROFILE = 'USER_UPDATE_PROFILE';
export const USER_UPDATE_PROFILE_FIELD = 'USER_UPDATE_PROFILE_FIELD';
export const USER_DELETE_PROFILE_FIELD = 'USER_DELETE_PROFILE_FIELD';

// UI MODALS
export const UI_MODALS_UPDATE_FIELD = 'UI_MODALS_UPDATE_FIELD';
export const UI_PROCESSING_UPDATE_FIELD = 'UI_PROCESSING_UPDATE_FIELD';
export const UI_LOADED_UPDATE_FIELD = 'UI_LOADED_UPDATE_FIELD';

// app constants
export const APP_CONFIG_TOGGLE_ASIDE = 'APP_CONFIG_TOGGLE_ASIDE';
export const INITIATE_LOADING = 'INITIATE_LOADING';
export const STOP_LOADING = 'STOP_LOADING';

export const FETCH_WEATHER = 'FETCH_WEATHER';
export const FETCH_WEATHER_INPROGRESS = 'FETCH_WEATHER';


export const FETCH_WEATHER_PROGRESS = 'FETCH_WEATHER_PROGRESS'
export const FETCH_WEATHER_COMPLETE = 'FETCH_WEATHER_COMPLETE';

